# Generated by Django 5.0.1 on 2024-03-06 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fileupload", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="uploader_email",
            field=models.EmailField(
                default="founders@rovaai.com",
                max_length=254,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="uploader_name",
            field=models.CharField(default="Rova Founders", max_length=100),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
