# Generated by Django 5.0.1 on 2024-03-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fileupload", "0002_uploadedfile_uploader_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(upload_to="uploads/%Y/%m/%d/%s"),
        ),
    ]
