# Generated by Django 5.0.1 on 2024-03-06 20:49

import fileupload.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fileupload", "0003_alter_uploadedfile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(upload_to=fileupload.models.email_directory_path),
        ),
    ]
