# Generated by Django 5.0.1 on 2024-02-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="auto_generated",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="category",
            name="cluster_id",
            field=models.IntegerField(default=-2),
        ),
        migrations.AddField(
            model_name="category", name="threshold", field=models.FloatField(default=1),
        ),
    ]
