# Generated by Django 5.0.1 on 2024-02-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KeyMetricTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("importance", models.TextField()),
                ("summary", models.TextField()),
                ("user_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SessionKeyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.IntegerField()),
                ("keymetric_id", models.IntegerField()),
            ],
        ),
    ]
