# Generated by Django 5.0.1 on 2024-02-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("keymetrics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionkeymetric",
            name="keymetric_name",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
