# Generated by Django 5.0.1 on 2024-02-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("keymetrics", "0002_sessionstoscores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionstoscores",
            name="ai_score",
            field=models.IntegerField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name="sessionstoscores",
            name="kpi_score",
            field=models.IntegerField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name="sessionstoscores",
            name="user_score",
            field=models.IntegerField(default=3, null=True),
        ),
    ]
