# Generated by Django 5.0.1 on 2024-02-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("keymetrics", "0003_alter_sessionstoscores_ai_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionstoscores",
            name="custom_score",
            field=models.IntegerField(default=3, null=True),
        ),
    ]
