# Generated by Django 5.0.1 on 2024-02-17 00:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("keymetrics", "0006_remove_sessionstoscores_custom_score_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sessionstoscores",
            old_name="custom_scores",
            new_name="custom_score",
        ),
    ]
