# Generated by Django 5.0.1 on 2024-02-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("keymetrics", "0007_rename_custom_scores_sessionstoscores_custom_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionstoscores",
            name="custom_score",
            field=models.TextField(default="", null=True),
        ),
    ]
