# Generated by Django 5.0.1 on 2024-02-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("keymetrics", "0009_alter_sessionstoscores_custom_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionstoscores",
            name="custom_score",
            field=models.TextField(default="{}", null=True),
        ),
    ]
